# -*- mode: ruby -*-
# vi: set ft=ruby :
# From https://github.com/black-project/black-packer/blob/master/vm.json

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.5"

required_plugins = %w( vagrant-hosts vagrant-hostmanager vagrant-vbguest landrush vagrant-cachier)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
  if not plugins_to_install.empty?
      puts "Installing plugins: #{plugins_to_install.join(' ')}"
      if system "vagrant plugin install #{plugins_to_install.join(' ')}"
          exec "vagrant #{ARGV.join(' ')}"
      else
          abort "Installation of one or more plugins has failed. Aborting."
      end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Box
  config.vm.box = "BaseBox"
  config.vm.hostname = 'BaseBox'

  config.cache.scope = :box

  # Network
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.network "private_network", type: "dhcp"

  config.landrush.enabled            = true
  config.landrush.guest_redirect_dns = true
  #config.landrush.host = "serverhost", "10.0.2.2"

  config.hostmanager.enabled     = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
  if vm.id
    `VBoxManage guestproperty get #{vm.id} "/VirtualBox/GuestInfo/Net/1/V4/IP"`.split()[1]
  end

    config.hostmanager.aliases = %w(
      config.vm.hostname
    )

  end

  # SSH
  config.ssh.forward_agent = true

  # Providers
  config.vm.provider "virtualbox" do |v, override|
    override.vm.box_url = "build/BaseBox.box"
    v.memory = "2048"
    v.cpus = "2"
    v.name = "BaseBox"
  end

  # Git
  if File.exists?(File.join(Dir.home, '.gitconfig')) then
    config.vm.provision :file do |file|
      file.source      = '~/.gitconfig'
      file.destination = '/home/vagrant/.gitconfig'
    end
  end
end
