---
- name: Remove Use DNS
  lineinfile: "state=absent dest=/etc/ssh/sshd_config
  line='UseDNS no'"
  tags: install

- name: Set default timeout to VM"
  lineinfile: "state=present dest=/etc/default/grub
  regexp='^GRUB_TIMEOUT=0$'
  line='GRUB_TIMEOUT=0'"
  tags: install

- name: Set installer
  lineinfile: "state=present dest=/etc/default/grub
  regexp='^GRUB_CMDLINE_LINUX=\"\"$'
  line='GRUB_CMDLINE_LINUX=\"debian-installer=en_US\"'"
  tags: install

- name: Update grub
  command: update-grub
  tags: install

- name: Update date
  shell: date > /etc/vagrant_box_build_time
  tags: install

- name: set Ubuntu keyserver
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Install sudo (Debian only)
  apt: pkg=sudo state=present
  when: ansible_distribution == 'Debian'

- name: Update package manager
  apt: update_cache=yes
  become: true

- name: Install NTP server
  apt: name={{ item }} state=present
  with_items:
    - ntp

- name: Upgrade apt
  apt: upgrade=full
  become: true
