package_names: libhttp-parser2.1,sublime-text-installer,gvfs-bin
package_repos:
  - ppa:gnome-terminator
  - ppa:webupd8team/sublime-text-2
  - ppa:webupd8team/sublime-text-3
  - ppa:djcj/screenfetch
  - ppa:dawidd0811/neofetch
  - deb [trusted=yes] https://repo.iovisor.org/apt/{{ansible_distribution_release}} {{ansible_distribution_release}}-nightly main
  - deb http://apt.kubernetes.io/ kubernetes-{{ansible_distribution_release}} main
