# An rc of 0 means the text was found
- name: Test OS for OrbStack
  shell: grep -qE "(orbstack)" /proc/version
  register: OrbStack
  ignore_errors: True
  no_log: True

- name: Summary step for OrbStack
  set_fact:
    orbstack: "{{ true if (not OrbStack.failed and OrbStack.rc == 0) }}"

- name: Upgrade tmux
  apt: name=tmux state=present

- name: Install Zsh and mosh
  apt:
    name: "{{ items }}"
    state: present
  vars:
    items:
    - mosh
    - zsh

- name: Add local developer group
  group: name={{user}} state=present

- name: Add local developer user account (Generic)
  user: name={{user}} group={{user}} groups=sudo,adm,docker,kvm append=yes shell=/bin/zsh state=present
  when: not orbstack

- name: Add local developer user account (OSX OrbStack)
  user: name={{user}} group={{user}} groups=sudo,adm,kvm append=yes shell=/bin/zsh state=present
  when: orbstack

- name: Add local developer ssh keys
  user: name={{user}} ssh_key_file=.ssh/id_ed25519 ssh_key_type=ed25519 generate_ssh_key=yes
  when: not orbstack

- name: Add developer SSH key
  authorized_key: user={{user}} key="{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  when: not orbstack

- name: Change sudo group to not need passwords
  lineinfile: dest=/etc/sudoers state=present line='{{user}} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Read the public key file for use with authorization
  set_fact:
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') | default('') }}"

- name: Authorize key with GitHub for {{ ansible_hostname }} {{ user }}
  local_action:
    module: github_key
    name: Access Key for {{ ansible_hostname }} {{ ansible_default_ipv4.address }} {{ ansible_default_ipv4.macaddress }}
    token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
  when: lookup('env', 'GITHUB_TOKEN') != ""

- name: Notify Github SSH key injection status
  debug:
    msg: "Github access was not activated, GITHUB_TOKEN was not set in the local machines environment variables"
    verbosity: 0
  when: lookup('env', 'GITHUB_TOKEN') == ""
