---
- name: Install rump and unikernel dev tooling
  apt: name={{ item }} update_cache=yes state=present
  with_items:
      qemu
      libxen

- name: Download Go 1.6
  get_url: url=https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz dest=/tmp/go1.6.linux-amd64.tar.gz

- name: Install Go 1.6 locally for user {{user}}
  unarchive: src=/tmp/go1.6.linux-amd64.tar.gz dest="/home/{{user}}" copy=no creates="/home/{{user}}/go/bin/go"

- name: Install dev tooling
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - git-extras
    - libboost-dev 
    - autoconf 
    - automake 
    - libtool
    - libssl-dev
    - pkg-config
    - bison 
    - g++
    - clang-format-3.6
    - flex 
    - default-jdk 
    - ant 
    - mercurial
    - libpcre3-dev
    - libgpm-dev
    - libsqlite3-dev
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - exuberant-ctags
    - x11-xserver-utils
    - gettext
    - unzip
    - python-pygments
    - graphviz
    - pandoc
    - xsel
    - nodejs

- name: Create symlink for nodejs so that older node software can use it
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Install ungit
  npm: name=ungit global=yes

- name: Upgrade to the latest npm
  npm: name=npm@latest global=yes
