- name: Add the git sources for recent versions
  apt_repository: repo='ppa:git-core/ppa'

- name: Add the TMUX sources for recent versions
  apt_repository: repo='ppa:pi-rho/dev'

- name: add the new docker gpg key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add repro for docker Ubuntu Trusty 
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main'

- name: Update Apt
  apt: update_cache=yes
