---
- name: Install general certs
  apt: name={{ item }} state=present
  with_items:
    - ca-certificates
    - apt-transport-https

- name: Create a ca-certs directory
  become: true
  file: path=/usr/local/share/ca-certificates/cacert.org state=directory

- name: Download CA Certs root certificate
  become: true
  get_url: url=http://www.cacert.org/certs/root.crt dest=/usr/local/share/ca-certificates/cacert.org/root.crt

- name: Download CA Certs class 3 certificate
  become: true
  get_url: url=http://www.cacert.org/certs/class3.crt dest=/usr/local/share/ca-certificates/cacert.org/class3.crt

- name: Update certificates
  become: true
  shell: /usr/sbin/update-ca-certificates -f

# Using apt-key within the ansible python code breaks on Ubuntu 14.04 due to openssl package dependencies breaking
- name: Add Docker GPG key
  command: bash -lc "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install Docker CE and it dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce

- name: Add the docker group
  group: name=docker gid=998 state=present

- name: Start Docker
  service: name=docker state=restarted
