---

- name: Add 16.04 Security repo and git toolsets ubuntu repositories
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - ppa:git-core/ppa
    - deb http://security.ubuntu.com/ubuntu xenial-security main universe

- name: Install rump and unikernel dev tooling, was 4.4 now 4.6
  apt: name={{ item }} state=present
  with_items:
      - qemu
      - libxen-dev
      - libxen-4.6

- name: Download Go 1.7.1
  get_url: url=https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz dest=/tmp/go1.7.1.linux-amd64.tar.gz

- name: Install Go 1.7.1 locally for user {{user}}
  unarchive: src=/tmp/go1.7.1.linux-amd64.tar.gz dest="/home/{{user}}" copy=no creates="/home/{{user}}/go/bin/go"

- name: Download ripgrep
  get_url: url=https://github.com/BurntSushi/ripgrep/releases/download/0.2.1/ripgrep-0.2.1-x86_64-unknown-linux-musl.tar.gz dest=/tmp/ripgrep.tar.gz

- name: Unpack ripgrep
  unarchive: src=/tmp/ripgrep.tar.gz dest=/tmp copy=no creates="/tmp/ripgrep-0.2.1-x86_64-unknown-linux-musl/rg"

- name: Install ripgrep to user bin
  command: mv /tmp/ripgrep-0.2.1-x86_64-unknown-linux-musl/rg /home/{{user}}/bin/rg

- name: Install dev tooling
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - git-extras
    - libboost-dev 
    - autoconf 
    - automake 
    - libtool
    - libssl-dev
    - pkg-config
    - bison
    - g++
    - clang-format-3.6
    - flex 
    - default-jdk 
    - ant
    - mercurial
    - libpcre3-dev
    - libgpm-dev
    - libsqlite3-dev
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - exuberant-ctags
    - x11-xserver-utils
    - gettext
    - unzip
    - python-pygments
    - graphviz
    - pandoc
    - xsel
    - jq

- name: Install thrift development tools for C++
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - automake
    - bison
    - flex
    - g++
    - git
    - libboost1.58-all-dev
    - libevent-dev
    - libssl-dev
    - libtool
    - make
    - pkg-config

