---
- name: Install core tooling for admin and access
  apt: name={{ item }} state=present
  with_items:
    - xauth
    - rsync
    - most
    - unzip
    - mosh
    - wget
    - curl
    - rxvt-unicode-256color 
    - vim 
    - tmux
    - multitail 
    - htop
    - glances
    - nmon
    - git
    - git-flow



- name: Download lnav at version 0.7.3
  command: wget -O /tmp/lnav-0.7.3-linux-64bit.zip https://github.com/tstack/lnav/releases/download/v0.7.3/lnav-0.7.3-linux-64bit.zip 

- name: Extract lnav archive at version 0.7.3
  unarchive: src=/tmp/lnav-0.7.3-linux-64bit.zip dest=/tmp copy=no creates=/tmp/lnav-0.7.3/lnav

- name: Copy extracted lnav 0.7.3 executable to /usr/local/bin
  copy: src=/tmp/lnav-0.7.3/lnav dest=/usr/local/bin/lnav

- name: SysDig install
  shell: curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash 
