---
- name: Install core tooling for admin and access
  apt: name={{ item }} state=present
  with_items:
    - xauth
    - rsync
    - most
    - unzip
    - mosh
    - wget
    - curl
    - rxvt-unicode-256color 
    - vim 
    - tmux
    - multitail 
    - htop
    - glances
    - nmon
    - git
    - git-flow
