---
- name: read vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        # "ansible_distribution" may be: "Debian", "SLES", "Ubuntu", "CentOS"
        # "ansible_distribution_version" may be: "9.0", "12.2", "16.04", "7.3.1611"
        # "ansible_distribution_major_version" may be: "9", "12", 16.04"
        # "ansible_os_family" may be: "Debian", "RedHat", "Suse"
        # Upper/lower case is important

        - "{{ ansible_distribution }}.{{ ansible_distribution_version }}.packagenames.yml"
        # results in: "SLES.12.2", "Ubuntu.16.04", "CentOS.7.3.1611", "Debian.8.7"

        - "{{ ansible_distribution }}.{{ ansible_distribution_major_version }}.packagenames.yml"
        # results in: "SLES.12", "Ubuntu.16", "CentOS.7", "Debian.9"

        - "{{ ansible_distribution }}.packagenames.yml"
        # results in: "Debian", "SLES", "Ubuntu", "CentOS"

        - "{{ ansible_os_family }}.packagenames.yml"
        # results in: "Debian", "Suse, "RedHat"

        - "default.packagenames.yml"
      paths: "./vars/"

- name: install OS Specific repositories
  apt_repository: repo='{{ item }}' update_cache=yes
  when: package_repos is defined
  with_items: "{{ package_repos }}"

- name: install OS Specific packages
  package: name='{{ package_names }}' state=present
  when: package_names is defined

- name: set Ubuntu keyserver
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: github keyserver
  apt_key: keyserver=keyserver.ubuntu.com id=23F3D4EA75716059

- name: Add Security repo and git toolsets ubuntu repositories
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - ppa:git-core/ppa
    - deb https://cli.github.com/packages stable main

- name: Install github CLI
  apt: 
    name: "{{ items }}"
    state: present
  vars:
    items:
    - gh

- name: Add JSon processing repos
  apt_repository: repo=ppa:duggan/jo update_cache=yes
  when: (ansible_architecture == "x86_64") and  (ansible_distribution != "Ubuntu") and (ansible_distribution_major_version != "18")

- name: Install rump and unikernel dev tooling, was 4.4 now 4.6
  apt: 
    name: "{{ items }}"
    state: present
  vars:
    items:
    - qemu
    - libxen-dev
    - libxen-4.6
  when: (ansible_distribution != "Ubuntu") and (ansible_distribution_major_version != "14")

- name: Create user ~/.local/bin directory
  file: path=/home/{{user}}/.local/bin state=directory group={{user}} owner={{user}}

- name: Check if Go 1.21.5 is installed
  shell: /home/{{user}}/go/bin/go version
  register: go_version
  failed_when: false
  changed_when: false

- name: Download Go 1.21.5
  get_url:
      url: https://storage.googleapis.com/golang/go1.21.5.linux-amd64.tar.gz
      dest: /tmp/go.linux-amd64.tar.gz
      force: true
  when: ("go1.21.5" not in go_version.stdout) and (ansible_architecture == "x86_64")

- name: Clean artifact path
  file:
    state: absent
    path: "/home/{{user}}/go"
  when: ("go1.21.5" not in go_version.stdout) and (ansible_architecture == "x86_64")

- name: Check for clean go directory
  stat: 
      path: "/home/{{user}}/go"
  register: goPath

- name: Install Go 1.21.5 locally for user {{user}}
  unarchive:
    src: /tmp/go.linux-amd64.tar.gz
    dest: "/home/{{user}}"
    group: "{{user}}"
    owner: "{{user}}"
    copy: no
  when: not goPath.stat.exists and ("go1.21.5" not in go_version.stdout) and (ansible_architecture == "x86_64")

- sysctl:
    name: kernel.panic
    value: '3'
    sysctl_file: /tmp/test_sysctl.conf
    reload: no

#- name: add the gorun command as a binary file handled for Linux
  #lineinfile: 
    #dest: /proc/sys/fs/binfmt_misc/register
    #line: ":golang:E::go::/usr/local/bin/gorun:OC"
    #regexp: "^:golang:E::go::/usr/local/bin/gorun:OC"
    #state: present
    #owner: root
    #group: root
    #mode: 0200

- name: Check if RipGrep 14.0.3 is installed
  shell: /home/{{user}}/.local/bin/rg -V
  register: rg_version
  failed_when: false
  changed_when: false

- name: Download RipGrep
  get_url: 
    url: https://github.com/BurntSushi/ripgrep/releases/download/14.0.3/ripgrep-14.0.3-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/ripgrep-x86_64-unknown-linux-musl.tar.gz
    force: true
  when: ("ripgrep 14.0.3" not in rg_version.stdout) and (ansible_architecture == "x86_64")

- name: Unpack RipGrep
  unarchive:
    src: /tmp/ripgrep-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp
    copy: no
    creates: "/tmp/ripgrep-14.0.3-x86_64-unknown-linux-musl/rg"
  when: ("ripgrep 14.0.3" not in rg_version.stdout) and (ansible_architecture == "x86_64")

- name: Set Ripgrep ownership
  file: dest=/tmp/ripgrep-14.0.3-x86_64-unknown-linux-musl/rg mode=a+x group={{user}} owner={{user}}
  when: ("ripgrep 14.0.3" not in rg_version.stdout) and (ansible_architecture == "x86_64")

- name: Install RipGrep to user {{user}} ~/.local/bin
  command: mv -f /tmp/ripgrep-14.0.3-x86_64-unknown-linux-musl/rg /home/{{user}}/.local/bin/rg
  when: ("ripgrep 14.0.3" not in rg_version.stdout) and (ansible_architecture == "x86_64")

- name: Check if git-delta 0.16.5 is installed
  shell: /home/{{user}}/.local/bin/delta -V
  register: delta_version
  failed_when: false
  changed_when: false

- name: Download git-delta
  get_url: 
    url: https://github.com/dandavison/delta/releases/download/0.16.5/delta-0.16.5-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/delta.tar.gz
    force: true
  when: ("delta 0.16.5" not in delta_version.stdout) and (ansible_architecture == "x86_64")

- name: Unpack git-delta
  unarchive:
    src: /tmp/delta.tar.gz
    dest: /tmp
    copy: no
    creates: "/tmp/delta-0.16.5-x86_64-unknown-linux-musl/delta"
  when: ("delta 0.16.5" not in delta_version.stdout) and (ansible_architecture == "x86_64")

- name: Set git-delta ownership
  file: dest=/tmp/delta-0.16.5-x86_64-unknown-linux-musl/delta mode=a+x group={{user}} owner={{user}}
  when: ("delta 0.16.5" not in delta_version.stdout) and (ansible_architecture == "x86_64")

- name: Install git-delta to user {{user}} ~/.local/bin
  command: mv -f /tmp/delta-0.16.5-x86_64-unknown-linux-musl/delta /home/{{user}}/.local/bin/delta
  when: ("delta 0.16.5" not in delta_version.stdout) and (ansible_architecture == "x86_64")

- name: Check if direnv 2.33.0 is installed
  shell: /home/{{user}}/.local/bin/direnv version
  register: direnv_version
  failed_when: false
  changed_when: false

- name: Download direnv 2.33.0
  get_url:
    url: https://github.com/direnv/direnv/releases/download/v2.33.0/direnv.linux-amd64
    dest: /home/{{user}}/.local/bin/direnv
    force: true
  when: ("2.33.0" not in direnv_version.stdout) and (ansible_architecture == "x86_64")

- name: Enable direnv
  file: dest=/home/{{user}}/.local/bin/direnv mode=a+x group={{user}} owner={{user}}
  when: ("2.33.0" not in direnv_version.stdout) and (ansible_architecture == "x86_64")

- name: Check if grv 0.3.2 is installed
  shell: /home/{{user}}/.local/bin/grv -version
  register: grv_version
  failed_when: false
  changed_when: false

- name: Download grv 0.3.2
  get_url:
    url: https://github.com/rgburke/grv/releases/download/v0.3.2/grv_v0.3.2_linux64
    dest: /home/{{user}}/.local/bin/grv
    force: true
  when: ("0.3.2" not in grv_version.stdout) and (ansible_architecture == "x86_64")

- name: Enable grv
  file: dest=/home/{{user}}/.local/bin/grv mode=a+x group={{user}} owner={{user}}
  when: ("0.3.2" not in grv_version.stdout) and (ansible_architecture == "x86_64")

- name: Check if golangci-lint 1.55.2 is installed
  shell: /home/{{user}}/.local/bin/golangci-lint --version
  register: golangci_lint_version
  failed_when: false
  changed_when: false

- name: Download golangci-lint 1.55.2
  get_url:
    url: https://github.com/golangci/golangci-lint/releases/download/v1.55.2/golangci-lint-1.55.2-linux-amd64.tar.gz
    dest: /tmp/golangci-lint-linux-amd64.tar.gz
    force: true
  when: ("1.55.2" not in golangci_lint_version.stdout) and (ansible_architecture == "x86_64")

- name: Unpack golangci-lint
  unarchive:
    src: /tmp/golangci-lint-linux-amd64.tar.gz
    dest: /tmp
    copy: no
    creates: "/tmp/golangci-lint-1.55.2-linux-amd64/golangci-lint"
  when: ("1.55.2" not in golangci_lint_version.stdout) and (ansible_architecture == "x86_64")

- name: Set golangci-lint ownership
  file: dest=/tmp/golangci-lint-1.55.2-linux-amd64/golangci-lint mode=a+x group={{user}} owner={{user}}
  when: ("1.55.2" not in golangci_lint_version.stdout) and (ansible_architecture == "x86_64")

- name: Install golangci-lint to user {{user}} ~/.local/bin
  command: mv -f /tmp/golangci-lint-1.55.2-linux-amd64/golangci-lint /home/{{user}}/.local/bin/golangci-lint
  when: ("1.55.2" not in golangci_lint_version.stdout) and (ansible_architecture == "x86_64")

- name: Install dev tooling
  apt:
    name: "{{ items }}"
    state: present
  vars:
    items:
    - git-extras
    - autoconf 
    - automake 
    - libtool
    - libssl-dev
    - pkg-config
    - bison
    - g++
    - flex
    - default-jdk 
    - ant
    - mercurial
    - ncurses-dev
    - libpcre3-dev
    - libgpm-dev
    - libsqlite3-dev
    - libssl-dev
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - exuberant-ctags
    - x11-xserver-utils
    - gettext
    - unzip
    - graphviz
    - pandoc
    - xclip
    - xsel
    - jq
    - grc
    - bashtop

- name: Install x86 specific dev tooling
  apt:
    name: "{{ items }}"
    state: present
  vars:
    items:
    - jo
  when: ansible_architecture == "x86_64"

- name: Add 16.04+ git toolsets ubuntu repositories
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - ppa:lazygit-team/daily
  when: (ansible_distribution != "Ubuntu") and (ansible_distribution_major_version != "14")

- name: Install dev packages not supported on Ubuntu 14.04
  apt:
    name: "{{ items }}"
    state: present
  vars:
    items:
    - lazygit
    - libboost-dev
  when: (ansible_distribution != "Ubuntu") and (ansible_distribution_major_version != "14")

- name: Install thrift development tools for C++
  apt:
    name: "{{ items }}"
    update_cache: yes
    state: present
  vars:
    items:
    - automake
    - bison
    - flex
    - g++
    - git
    - libevent-dev
    - libssl-dev
    - libtool
    - make
    - pkg-config
    - zlibc
    - zlib1g
    - zlib1g-dev
  when: (ansible_distribution != "Ubuntu") and (ansible_distribution_major_version < "23")

- name: Install Ruby development tools
  apt: 
    name: "{{ items }}"
    update_cache: yes
    state: present
  vars:
    items:
    - ruby
    - ruby-dev
  when: ansible_architecture == "x86_64"
